---
- hosts: all
  tasks:
    - name: install updates
      yum: name=* state=latest
    - name: install nginx
      become: yes
      yum: name=nginx state=latest
    - name: starting nginx
      become: yes
      service: name=nginx state=started
